---
name: luals-addon-luassert
description: Lua language server addon for luassert
homepage: https://github.com/LuaCATS/busted
licenses:
  - MIT
languages:
  - Lua
categories:
  - LSP
source:
  id: pkg:github/LuaCATS/luassert@main
  build:
    run: |
      #
share:
  luals-addons/addonManager/addons/luassert/module/library/: library/
