---
name: rustledger-lsp
description: Language Server Protocol (LSP) implementation for Beancount files.
homepage: https://github.com/rustledger/rustledger
licenses:
  - GLP-3.0-only
languages:
  - Beancount
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:github/rustledger/rustledger@v0.10.1
  build:
    - target: unix
      run: |
        cargo build --release -p rustledger-lsp
      bin: target/release/rledger-lsp
    - target: win
      run: |
        cargo build --release -p rustledger-lsp
      bin: target/release/rledger-lsp

bin:
  rledger-lsp: "{{source.build.bin}}"

neovim:
  lspconfig: rledgerls
