---
name: rustledger-lsp
description: Language Server Protocol (LSP) implementation for Beancount files.
homepage: https://github.com/rustledger/rustledger
licenses:
  - GLP-3.0-only
languages:
  - Beancount
categories:
  - LSP

source:
  id: pkg:cargo/rustledger-lsp@0.14.1

bin:
  rledger-lsp: cargo:rledger-lsp

neovim:
  lspconfig: rledgerls
