---
name: luals-addon-busted
description: Lua language server addon for busted
homepage: https://github.com/LuaCATS/busted
licenses:
  - MIT
languages:
  - Lua
categories:
  - LSP
source:
  id: pkg:github/brunotvs/busted-luals-addon@main
  build:
    run: |
      #
share:
  luals-addons/addonManager/addons/busted/module/library/: library/
