---
name: busted
description: Lua unit testing framework
homepage: https://github.com/lunarmodules/busted
licenses:
  - MIT
languages:
  - Lua
categories:
  - Runtime
source:
  id: pkg:github/lunarmodules/busted@master
  build:
    run: |
      :
  bin: bin/busted
bin:
  busted: "{{source.bin}}"
